auctions/urls.py
from django.urls import path
from django.contrib import admin

from . import views

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("auction/<int:id>/", views.show, name="show"),
    path("category/<str:name>/", views.category, name="category"),
    path("categories", views.categories, name="categories"),
    #dynamic page
    path("", views.index, name="index"),
    #auth req
    path("new", views.register, name="new"),
    path("bid", views.bid, name="bid"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("admin/", admin.site.urls),
    path("comment", views.comment, name="comment"),
    path("auction/new", views.new, name="new"),
    path("auction/close/<int:id>", views.close, name="close")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    """class for user objects (users)"""


class Auction(models.Model):
    """class for managing auctions"""
    # auction data
    title = models.CharField(max_length=200)
    description = models.TextField()
    img_url = models.TextField()
    price = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    closed = models.BooleanField('Closed', default=False)
    # foreign keys
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        null=True
        )
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    winner = models.ForeignKey(
        'User',
        on_delete=models.PROTECT,
        null=True,
        related_name="auction_winner"
        )

    def __str__(self):
        return self.title


class Category(models.Model):
    """class for an auction's category"""
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Bid(models.Model):
    """class for bid records"""
    amount = models.IntegerField('Amount', default=0)
    # foreign keys
    auction = models.ForeignKey('Auction', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} in {self.auction} bid amount {self.amount}"


class Wauction(models.Model):
    """class for recording user's watched auctions and history"""
    active = models.BooleanField('Active', null=True)
    # foreign keys
    auction = models.ForeignKey('Auction', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return str(f"{self.user.username} wauction {self.auction.title}")


class Comment(models.Model):
    """class for auction comment"""
    content = models.TextField('Content', blank=True)
    # foreign keys
    auction = models.ForeignKey('Auction', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(
            f"{self.user.username} said {self.content} on {self.auction.title}"
            )

auctions/forms.py
from django import forms

from .models import Category, Bid, Auction, Comment


class CommentForm(forms.ModelForm):
    """create comment form"""
    class Meta:
        model = Comment
        fields = ["user", "auction", "content"]
        widgets = {
            "user": forms.HiddenInput(),
            "auction": forms.HiddenInput(),
            "content": forms.Textarea()
            }


class AuctionForm(forms.Form):
    """create auction form"""
    title = forms.CharField(label="Title")
    price = forms.CharField(widget=forms.NumberInput, label="Price")
    img_url = forms.CharField(label="Image Url", required=False)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False
        )
    description = forms.CharField(widget=forms.Textarea, label="Description")
    closed = forms.BooleanField(
        widget=forms.CheckboxInput(), label="End Auction", required=False
    )


class WauctionForm(forms.Form):
    """create or remove auction from watchlist form"""
    auction = forms.CharField(widget=forms.HiddenInput, label="Auction")
    active = forms.BooleanField(
        widget=forms.CheckboxInput(), label="Add to Watchlist", required=False
    )


class BidForm(forms.ModelForm):
    """create bid record form"""
    class Meta:
        model = Bid
        fields = ["user", "auction", "amount"]
        widgets = {"auction": forms.HiddenInput(), "user": forms.HiddenInput()}


class EndAuctionForm(AuctionForm):
    """end auction form (set closed to True)"""
    class Meta:
        model = Auction
        fields = ["closed"]
        widgets = {"closed": forms.CheckboxInput()}

auctions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import AuctionForm, WauctionForm, BidForm, EndAuctionForm, CommentForm
from .models import User, Auction, Bid, Category, Wauction, Comment


def show(request, id):
    """finds auction data and returns forms if user is logged_in"""
    user = request.user
    auction = Auction.objects.get(id=id)
    comments = Comment.objects.filter(auction=auction)
    highest_bidder = get_highest_bidder(auction)
    number_of_bids = get_number_of_bids(auction)
    if user.is_authenticated:
        user = User.objects.get(username=user)
        # make forms
        if Wauction.objects.filter(user=user, auction=auction).exists():
            wauction = Wauction.objects.get(user=user, auction=auction)
            active = wauction.active
        else:
            wauction = Wauction(user=user, auction=auction)
            active = False
        wauction_obj = {"auction": auction.id, "active": active}
        bid_form = BidForm({"auction": auction,
                            "user": user,
                            "amount": auction.price
                            })
        end_auction_form = EndAuctionForm({"closed": auction.closed})
        comment_form = CommentForm({"auction": auction, "user": user})
        # return auction forms and data
        return render(
            request,
            "auctions/show.html",
            {
                "auction": auction,
                "wauction_form": WauctionForm(wauction_obj),
                "bid_form": bid_form,
                "end_auction": end_auction_form,
                "comment_form": comment_form,
                "comments": comments,
                "number_of_bids": number_of_bids,
                "highest_bidder": highest_bidder,
                "is_current_user_winner": user == auction.winner,
                "is_current_user_owner": user == auction.user
            }
        )
    # return auction data
    return render(
        request,
        "auctions/show.html",
        {
            "auction": auction,
            "wauction_form": WauctionForm(),
            "bid_form": BidForm(),
            "end_auction": EndAuctionForm(),
            "comments": comments,
            "number_of_bids": number_of_bids,
            "highest bidder": highest_bidder,
            "is_current_user_winner": False,
            "is_current_user_owner": False
        }
    )


def index(request):
    """return active auctions"""
    return render(request, "auctions/index.html", {
        "auctions": Auction.objects.filter(closed=False)
        })


def category(request, name):
    """return list of active auctions in category"""
    auctions = Auction.objects.filter(category__name=name)
    return render(
            request,
            "auctions/category.html",
            {"name": name, "auctions": auctions}
        )


def categories(request):
    """return list of categories"""
    category_list = Category.objects.all()
    # get list of category names
    return render(
            request,
            "auctions/categories.html",
            {"category_list": category_list}
        )


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request,
                "auctions/register.html",
                {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url='login')
def new(request):
    """create new auction from auction form or return form error"""
    if request.method == "GET":
        return render(request, "auctions/new.html", {"form": AuctionForm()})
    else:
        form = AuctionForm(request.POST)
        if form.is_valid():
            auction = Auction(**form.cleaned_data)
            auction.user = request.user
            auction.save()
            return HttpResponseRedirect(reverse("index"))

        else:
            return render(request, "auctions/new.html", {"form": form})


@login_required(login_url='login')
def comment(request):
    """create comment and return to previous page"""
    user = request.user
    if request.method == "POST":
        if user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                # auction = form.cleaned_data["auction"]
                # check if it's a duplicate and that it has some content
                if form.cleaned_data["content"]:
                    if not is_comment_duplicate(user, form):
                        form.save(commit=True)
                    else:
                        messages.add_message(
                            request,
                            messages.ERROR,
                            'This comment is a duplicate.'
                        )
                else:
                    messages.add_message(
                            request,
                            messages.ERROR,
                            'Comment must not be empty.'
                        )
    return redirect(request.META.get(
        'HTTP_REFERER',
        'redirect_if_referer_not_found'
        ))


@login_required(login_url='login')
def close(request, id):
    """close auction and assign winner variable to the highest_bidder"""
    auction = Auction.objects.get(id=id)
    auction.closed = True
    # rewrite method
    if not get_highest_bidder:
        auction.winner = request.user
    else:
        auction.winner = get_highest_bidder(auction)
    auction.save()
    return redirect("/auction/{}".format(id))


@login_required(login_url='login')
def bid(request):
    """create bid object or pass error message and refresh page"""
    form = BidForm()
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            auction = form.cleaned_data["auction"]
            if auction.price < float(form.cleaned_data["amount"]):
                auction.price = float(form.cleaned_data["amount"])
                auction.save()
                form.save(commit=True)
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Bid amount must be greater than auction price.'
                    )
    return redirect(request.META.get(
            'HTTP_REFERER',
            'redirect_if_referer_not_found'
            ))


@login_required(login_url='login')
def watchlist(request):
    """if request is get return list of users watchlist items,
    else create watched auction object and refresh page"""
    # if user is logged_in
    # display user's watchlist
    user = request.user
    if user.is_authenticated:
        if request.method == "GET":
            # check if there are any wauctions
            if Wauction.objects.filter(user=user, active=True).exists():
                wauctions = Wauction.objects.filter(user=user, active=True)
                # get watched auction items where user=user and active=true
                if wauctions.count() > 1:
                    # get auction items from watched auction items
                    return render(
                        request,
                        "auctions/watchlist.html",
                        {"auctions": wauctions}
                        )
                auction = wauctions[0].auction
                return render(
                    request,
                    "auctions/watchlist.html",
                    {"auction": auction}
                    )
            else:
                return render(
                    request,
                    "auctions/watchlist.html",
                    {"auctions": []}
                    )
        else:
            auction_id = int(request.POST["auction"])
            auction = Auction.objects.get(pk=auction_id)
            wauction, created = Wauction.objects.get_or_create(
                user=user, auction=auction
            )
            wauction.active = not bool(wauction.active)
            wauction.save()
            return redirect("/auction/{}".format(auction.id))

    else:
        return redirect("index")


# extract these into the model
def get_highest_bidder(auction):

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>

        {% for category in category_list %}
            <li><a href="{% url 'category' category.name %}"> {{ category.name }} </a></li>
        {% endfor %}

{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>{{ name }}</h2>

        {% for auction in auctions %}
            <li><a href="{% url 'show' auction.id %}"> {{ auction.title }} </a></li>
        {% endfor %}

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div class="grid-container">
        {% for auction in auctions %}
        <div class="grid-item">
            <div class="card">
                <a href="{% url 'show' auction.id %}"><img src="{{auction.img_url}}"  alt="Auction Image" style="width:100%"></img></a>
                <div class="container">
                    <p><a href="{% url 'show' auction.id %}">{{ auction.title }} </a></p>
                    <p>Created {{auction.created_date}}</p>
                    <p>Current Bid ${{auction.price}}</p>
                    <p>Category: {{auction.category}}</p>
                    <p>Description: {{auction.description}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/watchlist">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/auction/new">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Create Listing</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    {% if user.is_authenticated %}
        <form action="/auction/new" method="post">
            {% csrf_token %}
            <p>Title: {{ form.title }}</p>
            <p>Price: {{ form.price }}</p>
            <p>Image Link: {{ form.img_url }}</p>
            <p>Category: {{ form.category }}</p>
            <p>Description: {{ form.description }}</p>
            
            <input type="submit">
        </form>
    {% else %}
        Not signed in.
    {% endif %}


{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/show.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="card">
    <div class="grid-container">
    <div class="grid-item">
            <img src="{{auction.img_url}}"></img>
            <div class="container">
            <li><a href="{% url 'show' auction.id %}"> {{ auction.title }} </a></li>
            <li>Created {{auction.created_date}}</li>

            <li>Category: {{auction.category}}</li>
            <li>Description: {{auction.description}}</li>
            {% if comments %}
                {% for comment in comments %}
                    <li>{{comment.user}} said {{comment.content}}</li>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
Current Bid ${{auction.price}}
Highest Bidder: {{ highest_bidder.username }}
Number of bids: {{number_of_bids}}
        <!-- if signed in  -->
        <!-- listing closed -->
            <!-- highest bidder = winner -->
            <!-- display winner or "you" -->   
        {% if auction.closed %}
            {% if is_current_user_winner %}<!-- if the user is the winner display "you won!" -->
                <p>You Won!</p>
            {% else %}
                <p>Winner is {{ auction.winner }} </p>
            {% endif %}
        {% else %}
        <!-- listing open -->
            <!-- if signed in and auction.user_id = request.user_id -->
                <!-- close auction -->
            {% if user.is_authenticated %}
                {% if is_current_user_owner %}
                    <form action="{% url 'close' auction.id %}" method="post" class="EndAuctionForm">
                        {% csrf_token %}
                        End Auction? {{ end_auction.closed }}
                        <input type="submit" style="visibility: hidden;">
                    </form>
                {% else %}
            
                    <form action="/bid" method="post" class="bidForm">
                        {% csrf_token %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                        {{ bid_form }}
                        <input type="submit" value="Bid" class="bid">
                    </form> 

                    <form action="/watchlist" method="post" class="WatchlistForm">
                        {% csrf_token %}
                        {{ wauction_form.as_p }}
                        <input type="submit" style="visibility: hidden;">
                    </form>

                    <form action="/comment" method="post" class="CommentForm">
                        {% csrf_token %}
                        Comment: {{ comment_form.content }}
                        {{comment_form.auction }}
                        {{comment_form.user }}
                        {{comment_form.errors}}
                        {{comment_form.non_field_errors}}
                        <input type="submit">
                    </form>

                {% endif %}   
            {% endif %}

        {% endif %}

            <!-- comment form -->

                <script type="text/javascript">  
                    $(function(){
                     $("#id_active").on('change',function(){
                        $('.WatchlistForm').submit();
                        });
                    });
                    $(function(){
                     $(".bid").on('change',function(){
                        $('.bidForm').submit();
                        });
                    });
                    $(function(){
                     $("#id_closed").on('change',function(){
                        $('.EndAuctionForm').submit();
                        });
                    });
                </script>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}


{% block body %}
    <h2>Watchlist</h2>
        {% if auctions %}
            {% for auction in auctions %}
                <li><a href="{% url 'show' auction.auction.id %}"> {{ auction.auction.title }} </a></li>
            {% endfor %}
        {% elif auction    %}
            <h3>Add some auctions to your watchlist to see them here.</h3>
        {% endif %}
{% endblock %}